#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. 
- A Series is a one-dimensional array-like object, 
- while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

![Insert Alt Text Here](images/3.pandas_python.png)

In [1]:
import pandas as pd

In [2]:
## Series
##A Pandas Series is a one-dimensional array-like object that can hold any data type. 
# It is similar to a column in a table.
# The first column in the output, 0, 1, 2, 3, 4, is the index of the Pandas Series

data=[1,2,3,4,5,10]

series=pd.Series(data)

print("Series \n",series)
print(type(series))

Series
 0     1
1     2
2     3
3     4
4     5
5    10
dtype: int64
<class 'pandas.Series'>

In [3]:
## Create a Series from dictionary
data={'a':1,'b':2,'c':3}

series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [4]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [7]:
## Dataframe
## create a Dataframe from a dictionary of list

data={
    'Name':['Kapil','John','Jack'],
    'Age':[25,30,45],
    'City':['Bangalore','New York','Florida']
}
# print(type(data))

df=pd.DataFrame(data)
# print(df)
print(type(df))
df['Age']

<class 'pandas.DataFrame'>

0    25
1    30
2    45
Name: Age, dtype: int64

**Difference between `df.loc` and `df.iloc`**

---

### 1. Selection basis
- **`df.loc`**  
  - Selects by **label** (row and column names).  
  - Includes both start and end of a slice.  
- **`df.iloc`**  
  - Selects by **integer position** (zero-based).  
  - End of a slice is **exclusive**.
---

### 3. Quick takeaways
- Use **`.loc`** when you know the **index/column names**.  
- Use **`.iloc`** when you want purely **positional** selection.

In [8]:
# 1.Sample DataFrame
df = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [40, 50, 60],
    'C': [70, 80, 90]
}, index=['row1', 'row2', 'row3'])

print(df)

       A   B   C
row1  10  40  70
row2  20  50  80
row3  30  60  90

In [11]:
#### a) Single-element access
#       0    1   2
#        A   B   C
# row1  10  40  70   # 0
# row2  20  50  80   # 1
# row3  30  60  90   # 2

# - **By label**:  
# df.loc['row2', 'B']      # → 50

# - **By position**:  
# df.iloc[1, 1]            # → 50 , direct print outputs in numpy format, print produces usable outputs
print(df.iloc[1,1])
# print(type(df.iloc[1,1]))

50

In [14]:
#### b) Row slicing
# - **Labels** (inclusive):  
# df.loc['row1':'row2']

# - **Positions** (end exclusive):  
df.iloc[0:2]    # start : end-1

       A   B   C
row1  10  40  70
row2  20  50  80

In [16]:
#### c) Column slicing
# - **Labels** (inclusive):  
# df.loc[:, 'A':'B']  #   : no restriction

# - **Positions** (end exclusive):  
df.iloc[:, 0:2] # start : end-1

       A   B
row1  10  40
row2  20  50
row3  30  60

In [18]:
df=pd.read_csv('sales_data.csv')

df.head(2)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal

In [19]:
# `df.tail(3)` shows the last 5 rows of your DataFrame `df`. It's a quick way to inspect the end of your data.
df.tail(3)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [20]:
### Accessing Data From Dataframe
# df

df['Product Name']

0                                        iPhone 14 Pro
1                                     Dyson V11 Vacuum
2                                     Levi's 501 Jeans
3                                    The Da Vinci Code
4                              Neutrogena Skincare Set
                            ...
235    Nespresso Vertuo Next Coffee and Espresso Maker
236                          Nike Air Force 1 Sneakers
237             The Handmaid's Tale by Margaret Atwood
238               Sunday Riley Luna Sleeping Night Oil
239                         Yeti Rambler 20 oz Tumbler
Name: Product Name, Length: 240, dtype: str

In [21]:
# `df.loc[0]` fetches the row in your DataFrame `df` that has the index label `0`.
df.loc[1]

# print(type(df.loc[0]))

Transaction ID                 10002
Date                      2024-01-02
Product Category     Home Appliances
Product Name        Dyson V11 Vacuum
Units Sold                         1
Unit Price                    499.99
Total Revenue                 499.99
Region                        Europe
Payment Method                PayPal
Name: 1, dtype: object

In [15]:
# `df.iloc[0]` gives you the first row of the DataFrame `df` as a Pandas Series.
df.iloc[0]

# print(type(df.iloc[0]))

Transaction ID              10001
Date                   2024-01-01
Product Category      Electronics
Product Name        iPhone 14 Pro
Units Sold                      2
Unit Price                 999.99
Total Revenue             1999.98
Region              North America
Payment Method        Credit Card
Name: 0, dtype: object

In [16]:
## Accessing a specified element
df.head(2)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal

In [17]:
df.at[0,'Product Name']

'iPhone 14 Pro'

In [18]:
df.at[1,'Product Category']

'Home Appliances'

In [19]:
## Accessing a specified element using iat
df.iat[1,0]

10002

In [20]:
df.head(2)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal

In [32]:
## Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Kapil','Age':32,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Bangalore'},
    {'Name':'Mukesh','Age':40,'City':'Bangalore'},
    {'Name':'Jack','Age':20,'City':'Bangalore'}
    
]
df=pd.DataFrame(data)

print(df)
print(type(df))

# ✔️ Tip: Always check len(your_list) == len(df) before assignment!
# len(df)

     Name  Age       City
0   Kapil   32  Bangalore
1    John   34  Bangalore
2  Mukesh   40  Bangalore
3    Jack   20  Bangalore
<class 'pandas.DataFrame'>

In [33]:
## Adding a column
salaries = [50000, 60000, 70000, 80000]  # correct
# salaries = [50000, 60000, 70000]   # error
df['Salary'] = salaries
df

     Name  Age       City  Salary
0   Kapil   32  Bangalore   50000
1    John   34  Bangalore   60000
2  Mukesh   40  Bangalore   70000
3    Jack   20  Bangalore   80000

In Pandas, these two parameters are essential for controlling **how** and **where** your data is modified.

### 1. `axis=1` (The Direction)
The `axis` parameter tells Pandas whether you want to drop a **row** or a **column**.

* **`axis=0` (Default):** Refers to the **horizontal axis (rows)**. If you use this, Pandas looks for index labels to remove.
* **`axis=1`:** Refers to the **vertical axis (columns)**. By setting `axis=1`, you are telling Pandas: "Look at the column headers and drop the one named 'Salary'."

> **Analogy:** Think of `axis=0` as a row of houses on a street, and `axis=1` as the vertical pillars holding up a roof.



---

### 2. `inplace=True` (The Storage)
By default, most Pandas operations **return a new object** and leave the original DataFrame untouched. `inplace` decides if the change happens "on the spot."

* **`inplace=False` (Default):** * The original `df` remains unchanged.
    * It creates a "copy" with the column removed.
    * *Usage:* `new_df = df.drop('Salary', axis=1)`
* **`inplace=True`:** * The operation modifies the original `df` directly.
    * It returns `None`. 
    * *Usage:* `df.drop('Salary', axis=1, inplace=True)`

---

### Summary Table

| Parameter | Value | What it does |
| :--- | :--- | :--- |
| **axis** | `1` | Targets **Columns** instead of Rows. |
| **inplace** | `True` | Updates the **original variable** directly; no need to re-assign. |

**Pro-Tip:** Modern Pandas practice is actually moving away from `inplace=True`. Many developers now prefer re-assigning the variable (e.g., `df = df.drop(...)`) because it is clearer and avoids certain "SettingWithCopy" warnings.

In [34]:
## Remove a column
df.drop('Salary',axis=1)
# df.drop('Salary',axis=1,inplace=True)

     Name  Age       City
0   Kapil   32  Bangalore
1    John   34  Bangalore
2  Mukesh   40  Bangalore
3    Jack   20  Bangalore

In [35]:
df

     Name  Age       City  Salary
0   Kapil   32  Bangalore   50000
1    John   34  Bangalore   60000
2  Mukesh   40  Bangalore   70000
3    Jack   20  Bangalore   80000

In [36]:
## Add age to the column
df['Age']=df['Age']+1
df

     Name  Age       City  Salary
0   Kapil   33  Bangalore   50000
1    John   35  Bangalore   60000
2  Mukesh   41  Bangalore   70000
3    Jack   21  Bangalore   80000

In [38]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [39]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
# `df.describe()` calculates and shows descriptive statistics 
# (like count, mean, standard deviation, min, max, and quartiles) for the **numerical columns** 
# in your DataFrame `df`. It gives you a quick overview of the data's distribution.
# print("Statistical summary:\n", df.describe())

Data types:
 Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object

In [41]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000